### ISSUE TITLE
除了写less, 其实压缩代码图片之类的,这些微信开发者工具已经有了, 而且工具直接可以less转wxss, 其他的并没有什么用感觉

### ISSUE THREAD

**Issue by peng-yin** [YangQiGitHub/wx-miniprogram-boilerplate#1]

**Comment by YangQiGitHub** [comment]
1. webstorm可以通过配置，将less直接转为wxss, VScode也有相关插件可以直接转换less，但是都不够灵活，通过gulp配置更灵活一些，可以引入更多第三方的lessUI库。
2. 开发者工具只能压缩JS，但不压缩图片。
