### ISSUE TITLE
请问node_modules和package.json是怎么移动到dist文件夹中的？

### ISSUE THREAD

**Issue by yellowChao** [YangQiGitHub/wx-miniprogram-boilerplate#11]
请问node_modules和package.json是怎么移动到dist文件夹中的？

├── dist         // 编译后目录
│    ├── miniprogram_npm  // 小程序npm构建生成
│    ├── node_modules     // 小程序模块依赖
│    ├── package-lock.json
│    ├── package.json
├── node_modules // 项目依赖
├── src 
├── package-lock.json
├── package.json
└── README.md

我看src和dist都有一份，从仓库代码看不出来怎么操作的，请问作者能透露下怎么操作的吗

**Comment by YangQiGitHub** [comment]
没有这种骚操作.
