### ISSUE TITLE
样式不生效

### ISSUE THREAD

**Issue by Regreless** [YangQiGitHub/wx-miniprogram-boilerplate#13]
下载源码,加了一个字体样式没有效果,整体的css效果都没效果

**Comment by YangQiGitHub** [comment]
可以具体描述一下吗？或者提供代码。

**Comment by Regreless** [comment]
我这边搞错了,wechat dev导入的是src导致写的样式不生效,其实应该导入dist,今天又下载试了一次样式是可以的

**Comment by YangQiGitHub** [comment]
> 我这边搞错了,wechat dev导入的是src导致写的样式不生效,其实应该导入dist,今天又下载试了一次样式是可以的

ok,虚惊一场，感谢反馈。
