### ISSUE TITLE
能否优化gulp编译速度

### ISSUE THREAD

**Issue by Venusjason** [YangQiGitHub/wx-miniprogram-boilerplate#4]
现在修改一个js文件，就会重新编译所有js，速度不是很快

**Comment by YangQiGitHub** [comment]
之前由于项目小巧，项目编译速度还说得过去，所以没有配置增量编译。增量编译的配置我会在后面版本加入。非常感谢issue！

**Comment by YangQiGitHub** [comment]
已经优化了编译速度，新增gulp增量编译。
