### ISSUE TITLE
如何区分开生产环境和开发环境呢？

### ISSUE THREAD

**Issue by jasonwwl** [YangQiGitHub/wx-miniprogram-boilerplate#5]
预览版、开发版与正式版有不同的两套API域名，如何做成配置文件区分开呢？

**Comment by YangQiGitHub** [comment]
我目前在项目中的用法是，创建了三个文件分别是development.js, production.js和testing.js，然后对应三个命令npm run dev, npm run build和npm run testEnv,不同的命令配置不同的域名。这样做尽管可以达到目的，但是感觉有点粗暴，并不是很优雅。所以就没push。大家有没有什么好的想法？

**Comment by YangQiGitHub** [comment]
这个功能已经更新啦。
