### ISSUE TITLE
重复@import sass文件

### ISSUE THREAD

**Issue by xmsz** [YangQiGitHub/wx-miniprogram-boilerplate#6]
例如
./a.scss
`@import c.scss`

./b.scss
`@import c.scss`

./c.scss
```
body{
    background:#000
}
```

输出会变成
./a.scss
```
body{
    background:#000
}
```
./b.scss
```
body{
    background:#000
}
```

而期望是
./a.scss
`@import c.scss`

./b.scss
`@import c.scss`

因为小程序本身就支持@import

**Comment by YangQiGitHub** [comment]
这是基于less的一套样式处理工作流，使用的gulp-less，然后更改文件拓展名.css为wxss，不支持@import。
