### ISSUE TITLE
带文件路径 生成模板 会多带了两层

### ISSUE THREAD

**Issue by AKA-BEN** [YangQiGitHub/wx-miniprogram-boilerplate#7]
![image](https://user-images.githubusercontent.com/26449827/47409081-49e9f080-d794-11e8-9a7e-018ed6ec5631.png)
![image](https://user-images.githubusercontent.com/26449827/47409105-5cfcc080-d794-11e8-85fc-43834f5e4f8d.png)

**Comment by YangQiGitHub** [comment]
目前不支持命令带文件路径，谢谢反馈。

**Comment by AKA-BEN** [comment]
![image](https://user-images.githubusercontent.com/26449827/48888942-343d1900-ee6f-11e8-93a4-b866ed7069b1.png)
把 `gulpfile.js`上面这一段改成下面这段就可以了
```
  const root = path.join(__dirname, 'src', type);
  let dirname = name, basename = name;

  if (name.indexOf('/') > -1) {
    let pathLastIndex = name.lastIndexOf('/');
    dirname = name.substr(0, pathLastIndex);
    basename = name.substr(pathLastIndex + 1);
  }

  return gulp
    .src(path.join(root, source, '*.*'))
    .pipe(
      rename({
        dirname: dirname,
        basename: basename
      })
    )
    .pipe(gulp.dest(path.join(root)));
```
